# Azure Pipelines YAML

stages:

# Source Stage
- stage: Source
  jobs:
  - job: SourceJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Build Docker image
        docker build -t testing:latest .
      displayName: 'Build Docker Image'
      
      # Additional steps as needed
      
# Deploy Stage
- stage: Deploy
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Connect to the VM using service connection
                ssh $(azureServiceConnectionName) '
                  # Stop existing containers
                  docker stop $(docker ps -q)
                  
                  # Remove existing containers
                  docker rm $(docker ps -a -q)
                  
                  # Run the new container
                  docker run -d --name=webserver -p 82:80 nginx
                '
            displayName: 'Deploy to VM'
