# Azure Pipelines YAML

stages:

# Source Stage
- stage: Source
  jobs:
  - job: SourceJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Build Docker image
        docker build -t testing:latest .
      displayName: 'Build Docker Image'
      
      # Additional steps as needed
      
# Deploy Stage
- stage: Deploy
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'test-app-ssh-conn'
              runOptions: 'commands'
              commands: 'sudo docker ps -a && docker container run -d --name=shivam -p 82:80 nginx'
              readyTimeout: '20000'
              
