# Azure Pipelines YAML

stages:

# Source Stage
- stage: Source
  jobs:
  - job: SourceJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Build Docker image
        docker build -t testing:latest .
      displayName: 'Build Docker Image'
      
      # Additional steps as needed
      
# Deploy Stage
- stage: Deploy
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              # Connect to the VM
              ssh $(vmUsername)@$(vmHostname) '
                # Stop existing containers
                docker stop $(docker ps -q)
                
                # Remove existing containers
                docker rm $(docker ps -a -q)
                
                # Run the new container
                docker run -d --name myapp $(dockerImageName)
              '
            displayName: 'Deploy to VM'
            env:
              vmPassword: $(vmPassword)
              
          # Additional steps as needed
